version: '3.8'

services:
  bot:
    build: .
    image: martingale-bot:latest
    container_name: dcabot

    # Load environment variables from external file
    # Edit bot.env to change settings, then: docker-compose restart
    env_file:
      - bot.env

    # Alternative: Specify variables directly here
    # environment:
    #   - API_KEY=${API_KEY}
    #   - API_SECRET=${API_SECRET}
    #   - SYMBOL=${SYMBOL}
    #   - TESTNET=${TESTNET}

    # Restart policy
    restart: unless-stopped

    # Optional: Mount logs directory
    # volumes:
    #   - ./logs:/app/logs

    # Resource limits (optional)
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

# For scheduled execution (cron-like)
# Uncomment this if you want periodic execution instead of continuous
#
# bot-cron:
#   build: .
#   image: martingale-bot:latest
#   env_file:
#     - bot.env
#   # Run every 5 minutes
#   command: |
#     sh -c "while true; do python main.py; sleep 300; done"
#   restart: unless-stopped
