# Docker Compose for Local SaaS Development
# Run: docker-compose up -d

version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: dcabot-postgres
    environment:
      POSTGRES_DB: dcabot_dev
      POSTGRES_USER: dcabot
      POSTGRES_PASSWORD: dcabot_dev_password
    ports:
      - "5435:5432"  # Using 5435 to avoid port conflicts
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./saas/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dcabot"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
