# Render.com Blueprint - SaaS Platform Only
# Branch: feature/saas-transformation
# Main branch (standalone bot) is deployed separately (not via Blueprint)

services:
  # Web Service (Flask dashboard)
  - type: web
    name: dcabot-saas-web
    env: python
    region: frankfurt
    plan: starter  # $7/month
    branch: feature/saas-transformation
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt -r requirements-saas.txt
      python saas/migrate.py
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT saas.app:app
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        sync: false  # Set in Render dashboard
      - key: SECRET_KEY
        generateValue: true
      - key: ENCRYPTION_KEY
        sync: false  # Set in Render dashboard
      - key: FLASK_ENV
        value: production
      - key: DEBUG
        value: false

  # Cron Job (executes all active bots every 5 minutes) - FREE!
  - type: cron
    name: dcabot-saas-scheduler
    env: python
    region: frankfurt
    schedule: "*/5 * * * *"  # Every 5 minutes
    branch: feature/saas-transformation
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt -r requirements-saas.txt
    startCommand: python saas/execute_all_bots.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        sync: false
      - key: ENCRYPTION_KEY
        sync: false

# ============================================================================
# DEPLOYMENT INFO
# ============================================================================
# Cost: $7/month (1 web service, 1 cron job is free)
# Region: Frankfurt (EU)
# URL: https://dcabot-saas-web.onrender.com
#
# Database: Digital Ocean PostgreSQL (diptrader)
# - Must allow Render IPs: 3.75.158.163, 3.125.183.140, 35.157.117.28,
#   74.220.51.0/24, 74.220.59.0/24
#
# Required env vars (set in Render dashboard):
# - DATABASE_URL: postgresql://diptrader:PASSWORD@host:25060/diptrader?sslmode=require
# - ENCRYPTION_KEY: Generate with Fernet.generate_key()
# - SECRET_KEY: Auto-generated by Render
#
# TO UPGRADE TO BACKGROUND WORKER (when >10 bots):
# - Change "type: cron" to "type: worker" in dcabot-saas-scheduler
# - Change "schedule" to "plan: starter"
# - Cost increases to $14/month ($7 web + $7 worker)
# ============================================================================

version: "1"
