# Render.com Blueprint Configuration
# Update env vars in Render dashboard for security
services:
- type: cron
  name: dcabot
  runtime: docker
  repo: https://github.com/pehur00/dcabot
  plan: starter
  envVars:
  # Required: Phemex API credentials
  - key: API_KEY
    sync: false
  - key: API_SECRET
    sync: false

  # Required: Trading configuration
  - key: SYMBOL
    sync: false
  - key: EMA_INTERVAL
    sync: false
  - key: TESTNET
    sync: false

  # Optional: Telegram notifications
  - key: TELEGRAM_BOT_TOKEN
    sync: false
  - key: TELEGRAM_CHAT_ID
    sync: false
  - key: BOT_STARTUP
    sync: false

  region: frankfurt
  schedule: '*/5 * * * *'  # Every 5 minutes (recommended)
  dockerContext: .
  dockerfilePath: ./Dockerfile
version: "1"
